### ISSUE TITLE
Slow speed of grabbing

### ISSUE THREAD

**Issue by reardenlife** [hbashton/spotify-ripper#46]
Apparently, the speed of ripping is somewhat close to 2x realtime.

```text
Progress: [====                          ] 00:55 / 05:29        (~02m 35s remaining)
Total:    [==                            ] 02:36:28 / 29:40:35  (~14h 56m remaining)
```

Is there any way ton improve on it?

**Comment by lavolp3** [comment]
You can decrease quality and bit size and it will improve a bit but you will not be able to improve it considerably. The treacks are not downloaded but streamed and recorded. You also will find that the ripping procedure gets thrown out if you stream from another device, because you can only stream from one device at a time.

**Comment by ramonskie** [comment]
well i can confirm that it was way faster last year..
so something in the backend must have changed.
but if i can remember correctly it was always `song play time / 3`
for downloading

**Comment by derblub** [comment]
+1 ..There has to be some kind of way around this limitation..

**Comment by derblub** [comment]
..That's one way, to solve an issue.

**Comment by lavolp3** [comment]
I think TO closed this since for him it resolved as a non-issue. 
I personally cannot confirm this. Grabbing seems to take the same time for me now as it did a year ago. 
But I'm using a fork with a bit different dependencies.

Have you tried to rip a playlist? What system are you using and does the song take longer or is there longer pauses?

**Comment by lavolp3** [comment]
@derblub there is no way for this repository to directly download the tracks. The site is at it is. Use a low cost SBC like a Raspberry Pi and let it run 24/7.

**Comment by derblub** [comment]
@lavolp3 I'm currently checking, if it's possible to implement multi-threaded streaming (maybe with multiple users). (eg. process 1 would start streaming at second:0, process 2 would start at 50%; merge once done).  
btw: What fork are you using? What's different?

**Comment by lavolp3** [comment]
> @lavolp3 I'm currently checking, if it's possible to implement multi-threaded streaming (maybe with multiple users). (eg. process 1 would start streaming at second:0, process 2 would start at 50%; merge once done).
> btw: What fork are you using? What's different?

Well, good idea, but as far as I know only one stream can run at a time. After all the spotify-ripper gets thrown out as soon as the user starts a stream on any other device.

**Comment by einheitsviktor** [comment]
FYI: Recently it has become possible to listen to the tracks, use the ripper AND change the devices without beeing thrown out.

**Comment by lavolp3** [comment]
How? Has something been changed in the code or is it a new feature of mopidy-spotify?

**Comment by einheitsviktor** [comment]
Cannot say. And I don't know if it was possible before but I can start more than one instance of spotify-ripper :)
